### ISSUE TITLE
Better way to manage telescope extensions

### ISSUE THREAD

**Issue by Builditluc** [pta2002/nixvim#10]
Currently, telescope extensions are all inside of the telescope.nix file. That means this file will get bigger and bigger the more extensions we add to it.

I would suggest we use separate files for the extensions just like with the lsp plugins. Would that be a good idea?

**Comment by pta2002** [comment]
Oh good idea, yes. Kind of like it's being done for LSP. Should probably do
it for treesitter, too. I'm kinda busy right now but I should be more free
to work on this after Christmas!

A quarta, 22/12/2021, 19:41, Builditluc ***@***.***> escreveu:

**Comment by Builditluc** [comment]
> I'm kinda busy right now
No problem, I can work on it.

**Comment by pta2002** [comment]
Thanks for the PR :) Fixed by #11
