### ISSUE TITLE
use without HM or nixos

### ISSUE THREAD

**Issue by edrex** [pta2002/nixvim#16]
I would like to use nixvim in a prototype runnable flake "env" project https://github.com/aquiferma/noter (see discussion [^0]). For this, I need a `myNeoVim` package with config/customizations baked in. 

There is a broader design need at the ecosystem level to define an ergonomic relationship between flakes and the module system outside the context of HM/nixos, but nixvim seems an OK place to pick up the conversation.

It seems like a "quick fix" might be to inline or maybe wrap one of the `programs.neovim` modules [^2][^3]. 

Also probably worth a look, @syberant's nix-neovim flake [^4], which IIUC inlines its own module system for config, and only calls `pkgs.wrappedNeoVim`.

[^0]: https://github.com/aquiferma/noter/issues/2
[^1]: https://github.com/pta2002/nixvim/blob/main/nixvim.nix
[^2]: https://github.com/nix-community/home-manager/blob/master/modules/programs/neovim.nix
[^3]: https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/neovim.nix
[^4]: https://github.com/syberant/nix-neovim/blob/main/flake.nix

**Comment by pta2002** [comment]
Hey, thanks for the pointers! This is actually something I've wanted to do for a while, but never quite figured out/had the patience to look into. It's definitely doable, so I'll look into what you suggested!

**Comment by syberant** [comment]
Hi! My flake does indeed use a separate module system for config (so no `program.nix-neovim.vim.g.showmode = false` but just `vim.g.showmode = false`).
Doing this is surprisingly easy as you can reuse the library functions implementing NixOS's module system (extra benefit: you can also automatically generate documentation a la `man configuration.nix`).
The relevant piece from my `flake.nix` is this part:
```nix
buildNeovim = { pkgs ? dpkgs, configuration }:
  let
    eval = evalModules {
      modules = getNixFiles ./modules ++ [
        (rec {
          _file = ./flake.nix;
          key = _file;
          config = {
            _module.args.pkgs = mkForce pkgs;
            _module.args.vimLib = import ./lib { lib = pkgs.lib; };
          };
        })

        configuration
      ];
    };
  in eval.config.product.binary;
```

Here `configuration` is your entry point configuration module, `evalModules` is just `pkgs.lib.evalModules` and `product.binary` is the [read-only option that contains the final executable](https://github.com/syberant/nix-neovim/blob/main/modules/product.nix).

To actually use the resulting binary you have to add something like `environment.systemPackages = [ (nix-neovim.buildNeovim { inherit pkgs; configuration = ./some-file.nix; }) ]` to your NixOS configuration.

Not really sure if this style is something you want but feel free to ask me any questions!

**Comment by pta2002** [comment]
I've been working on this on the standalone branch, if you want to check it out! As far as I can tell, the only thing left to support on this branch are the home-manager and NixOS modules. However, if you use it, you can generate a package derivation like this:

```nix
{
  outputs = { self, nixvim, ... }: {
    nvim-with-gruvbox = nixvim.build {
      colorschemes.gruvbox.enable = true;
    };
  };
}
```

If you have any questions please ask!
