### ISSUE TITLE
Error when using nixos Module

### ISSUE THREAD

**Issue by gador** [pta2002/nixvim#17]
I am getting `error: The option 'programs.neovim.extraConfigLua' does not exist.` when importing the module using flakes with `inputs.nixvim.nixosModules.nixvim`. This happens, even when not adding 
```
programs.nixvim.enable = true
```
Using homeManager works without issues.

Could it be that 
https://github.com/pta2002/nixvim/blob/f534819885f4cf8a878f4411a5e72e807f135acf/nixvim.nix#L260-L265

should reference `programs.nixvim` instead of `programs.neovim`? The official nixos neovim module does not have `extraConfigLua` and this probably causes the error.

**Comment by pta2002** [comment]
Should be fixed!
