### ISSUE TITLE
Options broken after #167

### ISSUE THREAD

**Issue by mikkel1156** [pta2002/nixvim#174]
**Plugin affected**: None
**Nixpkgs channel**: 22.11.20221211.dfef2e6 (Raccoon)
**Home-manager version**: 22.11

## Description
After updating my home-manager config (adding some packages to my system), I found neovim throwing errors for the options.
```
Error detected while processing /home/zero/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0: Invalid option type 'boolean' for 'syntax', should be string
stack traceback:
        [C]: in function 'error'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '_set'
        vim/_meta.lua: in function '__newindex'
        /home/zero/.config/nvim/init.lua:44: in main chunk
```
And saying options doesn't exist
```
Error detected while processing /home/zero/.config/nvim/init.lua:
E5113: Error while calling lua chunk: vim/_meta.lua:0: no such option: 'noswapfile'
stack traceback:
        [C]: in function 'nvim_get_option_info'
        vim/_meta.lua: in function '__index'
        vim/_meta.lua: in function ''
        vim/_meta.lua: in function '__newindex'
        /home/zero/.config/nvim/init.lua:44: in main chunk
```

I found that setting my revision for fetchGit to 96c77f126f40c08e4309b3b70305641265c34b2d fixes it (last commit before #167), and setting the revision to 6e54dc1143539fc5f6d4f963a41b39e84ddf99ef then the issue appears.

This doesn't look good for stability. 

## Config
Relevant config
```
options = {
      encoding = "utf8";
      syntax = true;

      number = true;
      relativenumber = true;

      noerrorbells = true;
      novisualbell = true;
      noswapfile = true;

      history = 1000;
      undodir = "~/.cache/nvim_undo/";

      shiftwidth = 4;

      timeout = true;
      timeoutlen = 300;
    };
```

**Comment by s1341** [comment]
‘Shouldn’t those ‘noxxx’ options be xxx = false’?

**Comment by mikkel1156** [comment]
> ‘Shouldn’t those ‘noxxx’ options be xxx = false’?

Don't think that's really related to the issue? But as I understand it, setting it to true will set the option (since they don't take a value). Even in the case they should be false, why does it need to crash then? It's unexpected behavior.

**Comment by s1341** [comment]
I think if you replace eg ‘novisualbell=true;’ with ‘visualbell=false;’ it might work. 

Perhaps we can make this problem less acute by wrapping the attribute setting line with the lua equivalent of a try/catch?

**Comment by mikkel1156** [comment]
> I think if you replace eg ‘novisualbell=true;’ with ‘visualbell=false;’ it might work.

Ah now I understand better. Might be worth adding it the documentation somewhere?

The syntax option was also broken for me, but I switched it to `syntax = "ON"` since it's expecting a string now.

**Comment by s1341** [comment]
Yeah. I agree that it’s not well documented. Although neovim lua docs do tell you to use this form. In any event, the try catch with a good warning would be a better user experience.

**Comment by pta2002** [comment]
Not sure there's any equivalent to a try/catch, but we can probably add some sort of warning in the Nix version that detects if you're trying to set an option that starts with 'no' and gives out a warning
