### ISSUE TITLE
Airline error 

### ISSUE THREAD

**Issue by gador** [pta2002/nixvim#18]
When using `plugins.airline.enable = true;` nix will throw an error:
```
error: ‘mkIf’ called with a non-Boolean condition
```
When adding `plugins.airline.powerline = true;` no error is thrown.
I believe 
https://github.com/pta2002/nixvim/blob/929659b7a115a7ea55a8e68786372ace071b45ad/plugins/statuslines/airline.nix#L46
should either be `true` or `false`

**Comment by pta2002** [comment]
Should be fixed!

**Comment by gador** [comment]
awesome :+1:
