### ISSUE TITLE
Nixos Module Broken

### ISSUE THREAD

**Issue by OrdoFlammae** [pta2002/nixvim#19]
Hi y'all. I'm not super experienced with Nix, so this may just be something that I don't quite understand, but I could not use this because I was getting errors along the lines of
```
> substituteStream(): WARNING: pattern 'Name=Neovim' doesn't match anything in file '/nix/store/mv12ajfnyndzdc1isj0kgmwdjm61n023-neovim-0.7.0/share/applications/nvim.desktop'
> /nix/store/zwrxbc3d1kzgnkqg0i0zn0fgakcw212a-hook/nix-support/setup-hook: line 110: /nix/store/fgicl65q7nz56jd5ngd5glsblgb1lq53-neovim-0.7.0/bin/nvim-python3: Permission denied
```

I Finally found this: https://discourse.nixos.org/t/help-needed-neovim-completions-fail-to-build/14223, and fixed the problem by setting `package = pkgs.neovim-unwrapped`. Shouldn't this be a default, if it doesn't work out-of-the-box? I don't entirely understand *why* this happens, though, so maybe I'm just mistaken.

**Comment by pta2002** [comment]
Hi, this isn't something I have experienced before, and I don't override
the default, but it might be a bug in the newer versions. I'll make sure to
check this out soon.

A quarta, 11/05/2022, 22:05, Aiden Loyd ***@***.***> escreveu:

**Comment by OrdoFlammae** [comment]
I think this is actually a much broader issue, and I'm still trying to pin it down exactly. It works fine with the setup in `home-manager` (which is what I think you use, looking at your dotfiles). However, with the setup in `nixos`, it breaks a number of things, of which this is just one. With the exact same config as with `home-manager`, it will install neovim, but it will not apply any configuration or plugins.

**Comment by OrdoFlammae** [comment]
Additional note: `home-manager` uses `neovim-unwrapped` by default as the base package, so that is why it isn't crashing and burning when you don't set it in that mode. The `nixos` module does no such thing.

**Comment by OrdoFlammae** [comment]
Status: I've figured out why the config is not being copied across, you have to add `customRC = configure.customRC` in the `neovimConfig` definition. Still working on why plugins are being ignored.

**Comment by pta2002** [comment]
Hey, finally have time to work on this, can you show me what your config looks like?

**Comment by OrdoFlammae** [comment]
nixvim.nix:
```nix
{ pkgs, ... }: {
  enable = true;

  colorscheme = "one";
  colorschemes.one.enable = true;

  plugins.airline.enable = true;

  plugins.lsp.enable = true;
  plugins.lsp.servers.rnix-lsp.enable = true;

  options = {
    shiftwidth = 2;
    tabstop = 2;
    expandtab = true;

    modeline = false;
  };

  extraConfigLua = ''
    vim.opt.formatoptions:remove('t')
    vim.opt.linebreak = true

    vim.api.nvim_command('filetype indent plugin on')
    vim.api.nvim_command('syntax on')
  '';

  extraPlugins = with pkgs.vimPlugins; [
    vim-nix
  ];
}
```

flake.nix:
```nix
{
  description = "My NixOS config";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
    nixvim.url = "github:pta2002/nixvim";
    home-manager.url = "github:nix-community/home-manager";
  };

  outputs = { self, nixpkgs, nixvim, home-manager, ... } @ inputs:
  let
    system = "x86_64-linux";

    pkgs = import nixpkgs {
      inherit system;

      config = {
        allowUnfree = true;
      };
    };
  in {
    nixosConfigurations = {
      ordoflammae-virtual = nixpkgs.lib.nixosSystem {
        inherit system;

        specialArgs = inputs;

        modules = [
          {
            boot = {
              loader.grub = {
                enable = true;
                version = 2;
                device = "/dev/sda";
              };

              initrd = {
                availableKernelModules = [ "ata_piix" "ohci_pci" "ahci" "sd_mod" "sr_mod" ];
                kernelModules = [ ];
              };

              kernelModules = [ ];
              extraModulePackages = [ ];
            };

            fileSystems = {
              "/" = {
                device = "/dev/disk/by-label/nixos";
                fsType = "ext4";
              };

              "/nixos" = {
                fsType = "vboxsf";
                device = "nixos";
                options = [ "rw" "nofail" ];
              };
            };

            swapDevices = [
              { device = "/dev/disk/by-label/swap"; }
            ];

            hardware.cpu.intel.updateMicrocode = false;
            virtualisation.virtualbox.guest.enable = true;

            nix = {
              package = pkgs.nixFlakes;
              extraOptions = ''
                experimental-features = nix-command flakes
              '';
            };

            networking = {
              hostName = "ordoflammae-virtual";
              useDHCP = false;
              interfaces.enp0s3.useDHCP = true;
            };

            users.users.ordoflammae = {
              isNormalUser = true;
              extraGroups = [ "wheel" "sudo" "vboxsf" ];
            };

            environment.systemPackages = with pkgs; [
              curl
              git
            ];

            imports = [ nixvim.nixosModules.nixvim ];

            programs.nixvim = import ./nixvim.nix { inherit pkgs; };

            system.stateVersion = "21.11";
          }
        ];
      };
    };
  };
}
```

My guess is that the reason you haven't seen this is that this is only an issue with `nixosModules`, and there are no issues when using the `home-manager` setup.

**Comment by pta2002** [comment]
Seems like it! As part of my work with #16, this should get fixed soon, since I am effectively redoing the whole non-HM setup from scratch.

**Comment by jhilker1** [comment]
I've noticed the same issue as well.

**Comment by pta2002** [comment]
For now, I'd recomend using the `standalone` branch, and not using the NixOS module, instead using the build function and putting it on `environment.systemPackages`:

```nix
{
  environment.systemPackages = [
    # ...
    (nixvim.build "x86_64-linux" {
      colorschemes.gruvbox.enable = true;
      # etc...
    });
  ];
}
```

This branch will get merged soon, I just need to get the NixOS and home-manager modules working, but the standalone `build` function is working perfectly fine!

**Comment by jhilker1** [comment]
i've been using it in home-manager and an alias to use my config

**Comment by OrdoFlammae** [comment]
> i've been using it in home-manager and an alias to use my config. As a side question, is it possible to use nix-colors to create a colorscheme in nixvim?

Please make a new issue for this, I know it's difficult on everyone (maintainer and future readers) when issues are not kept on-topic.

**Comment by jhilker1** [comment]
alright, my bad.

**Comment by pta2002** [comment]
> As a side question, is it possible to use nix-colors to create a colorscheme in nixvim?

There isn't any nix-colors module right now, but I can add one. If you have any extra requests regarding it though, or some idea for how it should work, please do create an issue though!

**Comment by dit7ya** [comment]
I tried to use this package today using the homeManager module but it failed with something like `programs.neovim.extraConfig` is no longer a valid option. Any help?
