### ISSUE TITLE
Packer extraconfig plugin [Feature Request/bug]

### ISSUE THREAD

**Issue by Knoc-Off** [pta2002/nixvim#233]
**Plugin affected**: plugins.packer
**Nixpkgs channel**: N/A
**Home-manager version**: N/A

## Description
Not entirely a bug-report, more a feature request, but installing simple plugins with packer is easy, but anything that is more than one line creates errors. the way I would like to use it, is to allow packer plugins to be a set, where you then have extra config options.

as an example: here is a plugin i would like to install, and the recommended way to do so is:
```
use {'tpope/vim-dispatch', opt = true, cmd = {'Dispatch', 'Make', 'Focus', 'Start'}}
```
but i cannot simply add this to the packer.plugins as a string, as it wont get recognized as lua. 

I instead suggest adding another option that takes a list of sets, and converts them into its own use(<name>, <extra config>) 
```
packer = { 
  enable = true;
  plugins = [
    "nvim-lua/plenary.nvim"
    "MunifTanjim/nui.nvim"
    "nvim-telescope/telescope.nvim"
    {
       name = "tpope/vim-dispatch";
       extraConfig = ''
         opt = true,
         cmd = {'Dispatch', 'Make', 'Focus', 'Start'}
         # Extra config for the plugin
       '';
    }
  ];
};
```

Hopefully this isn't a big-ask, and i might try my hand at implementing it myself, but im somewhat new to this. 
Thanks for developing the fantastic project i hope to see it grow!

**Comment by pupbrained** [comment]
Was just running into this same problem with [silicon.nvim](https://github.com/krivahtoo/silicon.nvim), it requires a 'run' option, but that doesn't seem to be possible in the current iteration of nixvim.

**Comment by GaetanLepage** [comment]
I made an update to the packer module.
It now supports all of the keys that you might want to use.
You will be able to find several examples here: https://github.com/pta2002/nixvim/blob/e89d919e4da844137b060c7bc7dc930c7e098d3c/tests/plugins/packer.nix

**Comment by traxys** [comment]
For completeness's sake, is  there any reason you still use packer ? nixvim should implement everything packer does more tightly into nixos I think.

**Comment by Knoc-Off** [comment]
> For completeness's sake, is there any reason you still use packer ? nixvim should implement everything packer does more tightly into nixos I think.

good point, i should look into how to better integrate with nix, but, for quick testing of a plugin or just not wanting to bother with setting something up long term. I think its nice to have the ability to use packer.
im still figuring everything out. just out of curiosity, how would you suggest installing such a plugin with nixvim?

**Comment by GaetanLepage** [comment]
> just out of curiosity, how would you suggest installing such a plugin with nixvim?

Either it has already been packages, and then, you can do:
```nix
programs.nixvim = {
  plugins.foo = {
    enable = true;
    optionA = valueA;
    ...
  };
};
```
