### ISSUE TITLE
Docs Request:  Usage with a devShell

### ISSUE THREAD

**Issue by MatrixManAtYrService** [pta2002/nixvim#240]
Is it possible to write a `flake.nix` which defines a devShell that works like so?

```
$ git clone github.com/some/project
$ cd project
$ nix develop
$ vim  # launches nixvim as configured by project/flake.nix
```

The docs seem to be about using flakes to configure your system, but I'm interested in the case where they're used to configure your project.

**Comment by dwarfmaster** [comment]
Using the `legacyPackages.${system}.makeNixvim`, you can create a nvim instance which has all its configuration bundled in it. It takes in argument a valid nixvim config and builds a package in which neovim is wrapped to use this config.

So you should be able to do something like:
```nix
  let
    vim = nixvim.legacyPackages.x86_64-linux.makeNixvim {
      plugins.lsp.enable = true;
      ...
    };
  in pkgs.mkShell {
    packages = [ vim ];
  }
```
You would have to launch it as `nvim`, not `vim` though.

**Comment by pta2002** [comment]
Yeah, it's what @dwarfmaster said, but I'll be adding this to the readme

**Comment by MatrixManAtYrService** [comment]
That works great, thank you!

**Comment by pta2002** [comment]
Done!
