### ISSUE TITLE
Set globals before plugin setup 🌠

### ISSUE THREAD

**Issue by Alexnortung** [pta2002/nixvim#26]
With #25 hopefully soon getting merged there will be a need to set globals before the plugin setup.
An example from the nvim-cmp wiki: https://github.com/hrsh7th/nvim-cmp/wiki/Menu-Appearance#how-to-add-visual-studio-code-codicons-to-the-menu
Currently we cannot achieve this, since globals are set up after plugin setup.

### solution 1 (best) ✅✅✅

Move the logic that sets globals before the plugin setups.
I think this would be the best solution as long as it won't break anything.

### solution 2 ✅

Make a new option that lets the user set globals that will be set before plugin setups.

I can make a PR for any of the solutions if one of them are okay 🤓

**Comment by pta2002** [comment]
I think the first option would be best, it's easier and does not break anything. However, I think it might also be helpful to add something like a `extraLuaPreConfig` so that we can add code that runs before anything else - not needed for this though, I can add that later!
