### ISSUE TITLE
extraSettings has no effect

### ISSUE THREAD

**Issue by mxkrsv** [pta2002/nixvim#273]
**Plugin affected**: lsp
**Nixpkgs channel**: unstable
**Home-manager version**: unstable

## Description
extraSettings attribute set has no effect for most servers (nothing changes in generated config after rebuild). I only found it to work with rust-analyzer.

## Config
Relevant part:
```nix
texlab = {
  enable = true;
  extraSettings = {
    build = {
      onSave = true;
      forwardSearchAfter = true;
      args = [ "-lualatex" ];
    };
    forwardSearch = {
      executable = "zathura";
      args = [ "%p" "--synctex-forward=%l:1:%f" ];
    };
    chktex = {
      onOpenAndSave = true;
    };
  };
};
```
Options don't really matter, just `a = true` wouldn't work too.

**Comment by traxys** [comment]
Indeed it would have only worked  for a few servers that have all the options included in nixvim like rust-analyzer or nil_ls. Note that should not use `extraSettings` for rust-analyzer, but plain `settings` as these are typedchecked  (whereas extraSettings would be directly forwarded to the server)
