### ISSUE TITLE
bufferline - guifg and guibg highlights are deprecated

### ISSUE THREAD

**Issue by varris1** [pta2002/nixvim#292]
**Plugin affected**:
bufferline

**Nixpkgs channel**: 
nixpkgs-unstable

## Description
Setting any bufferline highlight will result in a warning at start because "guifg" and "guibg" are deprecated.

```
Using `gui`, `guifg`, `guibg`, `guisp` is deprecated please, convert these as follows: 
- guifg -> fg
- guibg -> bg
- guisp -> sp
- gui -> underline = true, undercurl = true, italic = true
 see :help bufferline-highlights for more details on how to update your highlights
Please fix: 
Press ENTER or type command to continue
- fill
```

## Config
[nixvim config](https://git.froggi.es/varris/dotfiles/src/commit/2de7c338ec7ad2af484533810467965f470be56e/user/configs/neovim/default.nix)

**Comment by GaetanLepage** [comment]
Fixed by https://github.com/pta2002/nixvim/pull/313
