### ISSUE TITLE
mappings `description` is not included by genMaps

### ISSUE THREAD

**Issue by andrevmatos** [pta2002/nixvim#299]
**Plugin affected**: 
**Nixpkgs channel**: unstable
**Home-manager version**: master

## Description
`description` field in `maps.*` doesn't get included in `config` param; it seems `helpers.genMaps` doesn't take them into account, even if they're described in mappings options. It'd be nice to rename it to `desc` as well, to be more in line with what people are used to in lua and disambiguate with nix options's `description`.

https://github.com/pta2002/nixvim/blob/dbd25dffd035974b37b0406a1d74c68040751344/lib/helpers.nix#L44-L77

**Comment by GaetanLepage** [comment]
Fixed by #300
