### ISSUE TITLE
Cannot set map options

### ISSUE THREAD

**Issue by Builditluc** [pta2002/nixvim#3]
When I try to change something in the maps option nix says the option does not exist.

My nixvim config:
```nix
maps = {
  normal."<leader>m" = {
    silent = true;
    action = "<cmd>make<CR>";
  };
};
```

the error message:
```
error: The option `home-manager.users.builditluc.programs.nixvim.maps.normal.<leader>m.action' does not exist. Definition values:
       - In `/Users/builditluc/.config/nixpkgs/home.nix': "<cmd>make<CR>"

       However there are no options defined in `home-manager.users.builditluc.programs.nixvim.maps.normal.<leader>m'. Are you sure you've
       declared your options properly? This can happen if you e.g. declared your options in `types.submodule'
       under `config' rather than `options'.
```

**Comment by pta2002** [comment]
This is interesting, can you share the rest of the config? As far as I
know, that's how it's defined in the example

A domingo, 21/11/2021, 10:25, Builditluc ***@***.***>
escreveu:

**Comment by Builditluc** [comment]
My config (NixVim settings start at ln. 117): 
https://gist.github.com/Builditluc/3053c0e34e58b57ff195c25ec812838a

**Comment by pta2002** [comment]
Just pushed a fix for this, tested it with your config and it works :) Thanks for reporting!
