### ISSUE TITLE
Plugin Request: nvim-ts-rainbow

### ISSUE THREAD

**Issue by cyntheticfox** [pta2002/nixvim#321]
**Plugin**: nvim-ts-rainbow
**Plugin repository**: https://github.com/p00f/nvim-ts-rainbow
**Is the plugin on nixpkgs**: Yes

## Extra information
Needs support for color options, and hard dependency on tree-sitter plugin

**Comment by GaetanLepage** [comment]
Done !
I chose to set the [nvim-ts-rainbow2](https://gitlab.com/HiPhish/nvim-ts-rainbow2) version by default because it seems to be the most maintained one.
