### ISSUE TITLE
error: attribute 'typst-lsp' missing

### ISSUE THREAD

**Issue by dch82** [pta2002/nixvim#332]
**Plugin affected**: None; General Issue
**Nixpkgs channel**: 22.11; Just downgraded from unstable
**Home-manager version**: 22.11

## Description
When I do `home-manager switch`, it prints an error message: 
```
$ home-manager switch
error: attribute 'typst-lsp' missing

       at /nix/store/pkqdh03yhmc3xs66maizqajr56cz1xxy-source/plugins/nvim-lsp/language-servers/default.nix:321:17:

          320|       description = "Enable typst-lsp for typst";
          321|       package = pkgs.typst-lsp;
             |                 ^
          322|     }
(use '--show-trace' to show detailed location information)
```
It may have to do with downgrade complications (I downgraded from unstable because the GNOME experience is more coherent with stable). `pkgs.typst-lsp` appears in the unstable repo but not 22.11
## Config
```
{
  enable = true;
  options = {
    mouse = "";
    number = true;
    shiftwidth = 2;
    expandtab = true;
    tabstop=2;
    autoindent = true;
    cursorline = true;
  };
  plugins.startify.enable = true;
  extraPlugins = with pkgs.vimPlugins; [
    vim-nix
    nerdtree
  ];
}
```
EDIT: It may be a home-manager issue as I disabled nixvim temporarily

**Comment by traxys** [comment]
Yeah we do not support unstable right now, but it should not be taken into account, I don't understand that part too well maybe @GaetanLepage knows ?

**Comment by GaetanLepage** [comment]
Indeed, this is caused by you not following nixos-unstable. We would like for you not having to follow unstable.
However, currently, the nixpkgs used by nixvim is the same as the one of home-manager.

**Comment by dch82** [comment]
OK... I went back to unstable, and all problems are solved.

**Comment by GaetanLepage** [comment]
You may follow [this issue](https://github.com/pta2002/nixvim/issues/333). If we find a better solution, it will be mentioned there.
