### ISSUE TITLE
Nix flake input ignored when using nixvim with home-manager and NixOS

### ISSUE THREAD

**Issue by GaetanLepage** [pta2002/nixvim#333]
When using the nixvim HM/NixOS modules, the `nixpkgs` input of the flake is ignored in favor of whatever version of `nixpkgs` is used by home-manager (or NixOS).
This has annoying consequences:
- A user following an older channel of `nixpkgs` or who did not updated his flake's inputs recently enough can suffer from bugs.
Example: #332 
- Oppositely, if a user updates his `nixpkgs`, and the latter contains vim plugins updates which are not compatible with nixvim can suffer from breakage/deprecation warnings.

Ideally, we would like nixvim to use its own `nixpkgs` input. This can let us (nixvim maintainers) pin `nixpkgs` to a version we know works and only update it carefully after some testing.
Users could still override this (at their own risk) by setting for instance `inputs.nixvim.inputs.nixpkgs.follows = "nixpkgs";`.

Note: when using the standalone nixvim wrapper, the behavior is correct. The problem is only present for the HM and NixOS modules.

**Comment by GaetanLepage** [comment]
After discussing with other home-manager contributors, it seems that we should keep on with the current behavior.
Indeed, home-manager modules are expected to use the same import of `nixpkgs` as home-manager.

Hence, we have decided to adopt the following approach: The `nixvim` repo will have two branches: `main` which is adapted to `nixos-unstable` users and a `23.05` branch for stable (`nixos-23.05`) users.
Note: this idea is from @traxys.
This strategy will be effective from the release of `nixos-23.05` [which should be around 05/22/2023](https://github.com/NixOS/nixpkgs/issues/223562).

**Comment by mikkel1156** [comment]
Thought about writing here instead of opening a new issue.

I there a way to get the effect you are mentioning? I'd like to keep my system on stable and only let nixvim use unstable packages.

Almost got it working using overlays to have the missing packages from unstable in nixpkgs. But some parts of the code use new lib features from unstable so it wasn't enough.

Right now I am using HM and NixOS with flakes.

**Comment by siph** [comment]
If you're willing to build a standalone config you can use whichever `nixpkgs` you want.

**Comment by mikkel1156** [comment]
> If you're willing to build a standalone config you can use whichever `nixpkgs` you want.

I tried using the makeNixvimWithModule function without success, it's giving me an error I can't find much info on.
```nix
nvim = nixvim.legacyPackages.${system}.makeNixvimWithModule {
        pkgs = import nixpkgs-unstable {
          inherit system;
          config.allowUnfree = true;
        };
        module = {
          config = {
            luaLoader.enable = true;
          };
        };
      };
```

```
error: The option `__ignoreNulls' does not exist. Definition values:
       - In `<unknown-file>': true
```

**Comment by siph** [comment]
If you generate an external config in it's own flake with:
```
nix flake init --template github:nix-community/nixvim
```

Then you can treat that as its own separate project with its own set of flake inputs. To use it in your NixOS configuration you can add it as a flake input to your NixOS flake and you can grab the derivations from the external flake (something like `inputs.nixvim-flake.packages.${system}.default;`).

**Comment by siph** [comment]
I wrote a small guide here: https://gist.github.com/siph/288b7c6b5f68a1902d28aebc95fde4c5

**Comment by GaetanLepage** [comment]
> I wrote a small guide here: https://gist.github.com/siph/288b7c6b5f68a1902d28aebc95fde4c5

Thank you very much for this guide !
Would you mind if we somehow include it in the default nixvim documentation ?

**Comment by siph** [comment]
> Thank you very much for this guide ! Would you mind if we somehow include it in the default nixvim documentation ?

Sure.
