### ISSUE TITLE
Bug: Undefined nix lib function

### ISSUE THREAD

**Issue by cyntheticfox** [pta2002/nixvim#338]
There's a `lib.concatLines` function called [here](https://github.com/pta2002/nixvim/blob/75a5e45b2b85a17e2c4b5f1e8d86f0552dff6abe/modules/editorconfig.nix#L51), but I don't see any such function defined elsewhere locally, and [some nixpkgs maintainers aren't amenable to these kinds of functions IMO](https://github.com/NixOS/nixpkgs/pull/209376#), so you'll probably need to create one like

```nix
{
  concatLines = builtins.concatStringsSep "\n";
}
```

**Comment by GaetanLepage** [comment]
The `concatLines` function is properly defined in `lib` here: https://github.com/NixOS/nixpkgs/blob/bf8dc7ed769798c06d585ba22bf8014d24ebefef/lib/strings.nix#L135-L144

Do you think that we should not be using it ?

**Comment by pta2002** [comment]
I'm with @GaetanLepage on this one, is there any particular reason we shouldn't be using functions defined in `nixpkgs`? I know it's not a builtin, but I don't really see any reason to make things harder for ourselves by skipping on them

**Comment by cyntheticfox** [comment]
It was added in January, so I suppose it's my fault for using stable... nevermind then
