### ISSUE TITLE
Can't use zls from flake

### ISSUE THREAD

**Issue by rupurt** [pta2002/nixvim#355]
**Plugin affected**: nvim-lsp
**Nixpkgs channel**: unstable
**Home-manager version**: 23.05-pre

## Description
I've installed the [zls](https://github.com/zigtools/zls/blob/master/flake.nix) flake with [zig-overlay](https://github.com/mitchellh/zig-overlay) to run the latest `zls` built on master. This appears to be successful because I now have the `zls` command that prints the latest version `0.11.0` which is not available in nikpkgs. I can't seem to understand why the `zls` command for the `nvim-lspconfig` then decides to start the `0.10.0` version available in nikpkgs.

```sh
> ls -l /proc/779460/exe
lrwxrwxrwx 1 alex alex 0 May  6 15:24 /proc/779460/exe -> /nix/store/5rplmy4k9iam2ixx5xxjcq8fp3a32pdq-zls-0.10.0/bin/zls
```

## Config
[My nixvim config](https://github.com/rupurt/nix-home/blob/main/modules/home-manager/neovim.nix)

**Comment by GaetanLepage** [comment]
I think that you could explicitly set `programs.nixvim.plugins.lsp.servers.zls.command` to the `zls` binary provided by th e`zig-overlay` flake input of your config.

**Comment by GaetanLepage** [comment]
More precisely:
```nix
{
  inputs = {
    nixvim.url = "github:pta2002/nixvim";
    zls.url = "github:zigtools/zls";
  };

  outputs = {
    self,
    nixvim,
    zls,
  }: let
    system = "x86_64-linux";

    nixvim' = nixvim.legacyPackages.${system};
    nvim =
      nixvim'.makeNixvimWithModule
      {
        module = {
          plugins = {
            lsp = {
              enable = true;

              servers = {
                zls = {
                  enable = true;
                  package = zls.packages.${system}.default;
                };
              };
            };
          };
        };
      };
  in {
    packages.${system}.default = nvim;
    apps.${system}.default = {
      type = "app";
      program = "${nvim}/bin/nvim";
    };
  };
}
```

**Comment by rupurt** [comment]
Thanks @GaetanLepage. I've tried adding this in both my home manager config and the project with devshell and it doesn't seem to work :{

**Comment by GaetanLepage** [comment]
Hmm do you mean that it keeps using the wrong version of `zls` ?
Could you have a look at the generated launch script for neovim ? (`cat $(which nvim)`)
The `$PATH` variable should be extended with the `/nix/store/xxxxxxxxxx-zls-11.0/bin` at some point.
Overriding the `package` means that this PATH is aiming at the provided package for the zls server.

**Comment by rupurt** [comment]
Yeah. It keeps using 0.10.0

```sh
PATH=${PATH/':''/nix/store/5rplmy4k9iam2ixx5xxjcq8fp3a32pdq-zls-0.10.0/bin'':'/':'}
PATH='/nix/store/5rplmy4k9iam2ixx5xxjcq8fp3a32pdq-zls-0.10.0/bin'$PATH
```

**Comment by GaetanLepage** [comment]
What exactly have you set the `package` to ?
Basically, if `zls-flake` is the name of the flake input that you have, the value for `package` should be `zls-flake.packages.YOUR_SYSTEM.default`.

**Comment by rupurt** [comment]
I've tried both what you recommended + inputs

```nix
package = zls.packages.${system}.default
```

```nix
package = inputs.zls.packages.${system}.default
```

```nix
package = inputs.zls-flake.packages.${system}.default
```

**Comment by GaetanLepage** [comment]
Have you updated your flake's inputs recently ?
For me, running `nix run github:zigtools/zls` starts the 0.11.0 version of zls...

**Comment by rupurt** [comment]
Yeah. I bumped all dependencies in flake.lock this week. I can get it to which with `nix run ...` + I can add the flake directly to the project and run `zls` in the terminal as version 0.11.0 but I can't get `nixvim` to run with 0.11.0.

**Comment by GaetanLepage** [comment]
I tried in my personal config (using the nixvim home-manager module):
1. Simply enabled the `zls` language server in nixvim. -> Running `nvim` and then `!zls --version` gives me `0.10.0`.
2. Apply [those changes](https://github.com/GaetanLepage/dotfiles/commit/7cdf969adb2e7f450d78d6eb5b1e3df83c573dbd) -> Running `nvim` and then `!zls --version` gives me `0.11.0`.

**Comment by rupurt** [comment]
You're an absolute legend @GaetanLepage. Thank you :pray:

It's working now. Looks like I can pick up a few tips from your dotfiles repo also.

**Comment by GaetanLepage** [comment]
Glad that it works !
Thank you for reporting the issue, it might help other people.

Happy hacking :)
