### ISSUE TITLE
Usage with Nix-colors

### ISSUE THREAD

**Issue by jhilker98** [pta2002/nixvim#37]
I'm currently using nix-colors for managing my color schemes, and I have been trying to use the [vim colorscheme function](https://github.com/Misterio77/nix-colors/blob/main/lib/contrib/default.nix#L38-L45) that nix-colors provides in order to use it. However, whenever I use it in my [config for nixvim](https://github.com/jhilker1/nixos-dots/blob/70e363ae16190d1e8631cf2d3945f8585d0c6935/users/jhilker/programs/nvim/default.nix), I get the same error of `error: colorscheme gruvbox-dark-hard not found`. What do I need to do to fix this?

**Comment by dwarfmaster** [comment]
I'll probably open a PR at some point, but for the moment you can copy [this](https://github.com/dwarfmaster/home-nix/blob/nixvim-setup/profiles/hm/programs/neovim/plugins/nix-colors.nix) to set it up. Another advantage is that you can just set lualine theme to `base16` and it just works with this plugin.

**Comment by jhilker1** [comment]
alright, I'll try that.

**Comment by GaetanLepage** [comment]
Is it relevant to add this feature to nixvim ?
If so, I guess I could easily port the implementation of @dwarfmaster or look for another solution.
Else, we might close this issue.

**Comment by jhilker98** [comment]
I will go ahead and close it - so far the implementation that @dwarfmaster has is working for me.

**Comment by GaetanLepage** [comment]
Ok good !
Feel free to come back if you feel that something is missing :)

**Comment by waot** [comment]
> If you're using an official base16 theme, you can do :
> 
> ```nix
> { config, lib, ... }:
> {
>   programs.nixvim = {
>     colorschemes.base16 = {
>       enable = true;
>       useTruecolor = true;
>       colorscheme = lib.toLower config.colorScheme.name;
>     };
>   };
> }
> ```
> 
> For a more robust solution, it would be possible to package [nvim-base16](https://github.com/RRethy/nvim-base16) and create a colorscheme based on it, since it directly takes the individual colors as arguments. I'll probably do that at some point if I find the time.

@dwarfmaster Does this also work for a custom Base16 setup, when i copy your code, it gives me an infinite recursion error.

**Comment by jhilker98** [comment]
I had also noticed infinite recursion with that setup, even when using an official colorscheme (gruvbox-dark-hard in my case).

**Comment by GaetanLepage** [comment]
@jhilker98, I tested the following setup and it works fine:
```nix
{ config, lib, ... }:
{
  programs.nixvim = {
    colorschemes.base16 = {
      enable = true;
      useTruecolor = true;
      colorscheme = "gruvbox-dark-hard";
    };
  };
}
```

Do you still encounter this issue ?

**Comment by jhilker98** [comment]
Yes, I was able to get it working now. Not totally sure what changed, but it works. :)

**Comment by dwarfmaster** [comment]
> > If you're using an official base16 theme, you can do :
> > ```nix
> > { config, lib, ... }:
> > {
> >   programs.nixvim = {
> >     colorschemes.base16 = {
> >       enable = true;
> >       useTruecolor = true;
> >       colorscheme = lib.toLower config.colorScheme.name;
> >     };
> >   };
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > For a more robust solution, it would be possible to package [nvim-base16](https://github.com/RRethy/nvim-base16) and create a colorscheme based on it, since it directly takes the individual colors as arguments. I'll probably do that at some point if I find the time.
> 
> @dwarfmaster Does this also work for a custom Base16 setup, when i copy your code, it gives me an infinite recursion error.

I am now using something based on `nvim-base16` that supports custom colors, see [here](https://github.com/dwarfmaster/home-nix/blob/master/modules/hm/nixvim-colors/default.nix). Note that I am not using `nix-colors` anymore but `stylix`, however the code should be easy to adapt.
