### ISSUE TITLE
plugins/completion/copilot: Package ‘nodejs-16.20.0’ is marked as insecure, refusing to evaluate

### ISSUE THREAD

**Issue by jfchevrette** [pta2002/nixvim#394]
**Plugin affected**: `copilot`
**Nixpkgs channel**: `unstable`
**Home-manager version**: `master`

## Description
`nodejs-16` was recently marked as insecure in nixpkgs-unstable. I was not able to pinpoint where and when that happened, but it was fine ~2 weeks ago

## Config
Probably not needed? I have `plugins.copilot.enable = true` and that's pretty much it

```
error: Package ‘nodejs-16.20.0’ in /nix/store/5ra5hcd4k79sd9b7qrfk3qy1qjf1p34f-source/pkgs/development/web/nodejs/v16.nix:13 is marked as insecure, refusing to evaluate.
```

I found `nodejs-16` is referenced here https://github.com/pta2002/nixvim/blob/246f811084886285696a96cdfc45f416af633449/plugins/completion/copilot.nix#L37

copilot.vim isn't explicit about what versions of nodejs are supported other than it [must be 16 or greater](https://github.com/github/copilot.vim/blob/1358e8e45ecedc53daf971924a0541ddf6224faf/autoload/copilot/agent.vim#L423)

**Comment by GaetanLepage** [comment]
Indeed, nodejs-16 is now EOL and thus has been marked as broken by nixpkgs maintainers.
To dismiss this warning, you could add the following to your NixOS config:
```nix
  nixpkgs.config.permittedInsecurePackages = [
    "nodejs-16.20.0"
  ];
```

**Comment by pta2002** [comment]
I'll close this since it's really an upstream Nixpkgs issue, not really a Nixvim issue

**Comment by jfchevrette** [comment]
@pta2002 I disagree this is a nixpkgs issue but perhaps my knowledge of nix/nixpkgs is too limited to see what you mean?

nixvim references `nodejs-16_x` which is EOL and has been marked as insecure in nixpkgs (not broken)

Please consider the PR I just opened or let me know what you think must be fixed in nixpkgs?

**Comment by pta2002** [comment]
Yeah, it was my bad, it's merged now :)
