### ISSUE TITLE
Plugin request: auto-save.nvim

### ISSUE THREAD

**Issue by DEEENGAN** [pta2002/nixvim#407]
**Plugin**: auto-save.nvim
**Plugin repository**: https://github.com/Pocco81/auto-save.nvim
**Is the plugin on nixpkgs**: vimPlugins.autosave-nvim

## Extra information
The README has some info about options and config under the section "configuration." It comes with defaults, which I have used and  enjoyed. Thank you in advance!

**Comment by GaetanLepage** [comment]
It seems that you have to update your flake's `nixvim` input to benefit from this recently added plugin.
