### ISSUE TITLE
Plugin request: indent-blankline.nvim

### ISSUE THREAD

**Issue by DEEENGAN** [pta2002/nixvim#408]
**Plugin**: indent-blankline.nvim
**Plugin repository**: https://github.com/lukas-reineke/indent-blankline.nvim/
**Is the plugin on nixpkgs**: vimPlugins.indent-blankline-nvim

## Extra information
The README has some info about options and config under the section "setup." It comes with defaults, which I have used and enjoyed. Thank you in advance!

**Comment by traxys** [comment]
This plugin is already packaged as `plugins.indent-blankline`
