### ISSUE TITLE
Treesitter nixvim injections only affects `extraConfigLua` & `extraConfigVim`

### ISSUE THREAD

**Issue by MattSturgeon** [pta2002/nixvim#449]
**Plugin affected**: treesitter
**Nixpkgs channel**: unstable
**Home-manager version**: 23.11-pre

## Description
Not sure whether to call this a bug or a request... It _feels_ like unintended behaviour or an edge-case that hasn't been considered...

The [current implementation](https://github.com/pta2002/nixvim/blob/01a45fd033417667b91b773188f55ca15072d407/plugins/languages/treesitter/treesitter.nix#L176-L196) for `plugins.treesitter.nixVimInjections` explicitly marks the content of a string assigned to "`extraConfigLua`" as "lua", but there's plenty of other strings in a nixvim config that contain lua code.

I'm not familiar enough with treesitter to suggest how to generalise the injection to other places, but it would be nice to have _if_ it's relatively low effort.

The example I've run into is key bind actions (global, nvim-cmp, lsp, etc). Normally such actions are simple enough that syntax highlighting isn't a deal breaker, but it would certainly make my nvim-cmp "super tab" bind more readable (for example):

```nix
nixvim.plugins.nvim-cmp = {
  enable = true;
  mapping = {
    "<CR>" = "cmp.mapping.confirm({ select = true })";
    "C-y" = "cmp.mapping.confirm({ select = true })";
    "<Tab>" = {
      modes = [ "i" "s" ];
      action = ''
        function(fallback)
          if cmp.visible() then
            cmp.select_next_item()
          elseif luasnip.expandable() then
            luasnip.expand()
          elseif luasnip.expand_or_jumpable() then
            luasnip.expand_or_jump()
          elseif check_backspace() then
            fallback()
          else
            fallback()
          end
        end
      '';
    };
    "<S-Tab>" = {
      modes = [ "i" "s" ];
      action = ''
        function(fallback)
          if cmp.visible() then
            cmp.select_prev_item()
          elseif luasnip.jumpable(-1) then
            luasnip.jump(-1)
          else
            fallback()
          end
        end
      '';
    };
  };
};
```

## Config
Your nixvim config

**Comment by traxys** [comment]
It's a bit difficult because in treesitter we only have the grammar, meaning that be can take desicions on the names. It's quite brittle also, as if you do
```
{
    extraConfigLua = let in ''
    '';
}
```
The code won't be highlighted. We can maybe try and match more cases, but I'm not sure we would be able to be exhaustive.

**Comment by pta2002** [comment]
Yeah it's the issue @traxys said, it's quite hard to match every case, it's already quite brittle as any config named `extraConfig*`, even from another module, would be highlighted...
