### ISSUE TITLE
lsp-lines error

### ISSUE THREAD

**Issue by Alexnortung** [pta2002/nixvim#45]
Attempting to use lsp-lines by enabling it results in a runtime error when you start neovim.

config:

```
plugins.lsp-lines.enable = true;
```

Error:

```
Error detected while processing /nix/store/x63x75izcri00gqir1r5ib1snmnhdj14-init.vim:
line  399:
E5108: Error executing lua [string ":lua"]:77: attempt to call field 'setup' (a nil value)
stack traceback:
        [string ":lua"]:77: in main chunk
```

It seems like `require('lsp_lines')` resolves to a nil value.

**Comment by pta2002** [comment]
This seems to only happen on `nixos-22.05`, but honestly I can't really figure out why... Maybe it's related to #44 and it didn't end up being a full fix, will have to investigate.

**Comment by pta2002** [comment]
This seems to only happen on `nixos-22.05`, but honestly I can't really figure out why... Maybe it's related to #44 and it didn't end up being a full fix, will have to investigate.

**Comment by Alexnortung** [comment]
I think this was a problem even before #44, but sure probably because I am using nixos-22.05.

I think it would be a good idea to make a bug template for GitHub so we can tell which Nixos  version we are using, so it will be easier to investigate bugs.

Things to put in the template:
Nixos version:
Home manager version:
Nixpkgs version for plugins:
Neovim version:

I really like this project and might make a pr for this template in the next couple og days 🥳🥳

🥳🥳🥳🥳🥳🥳🥳🥳🥰🥰🥰🥰🥰🥰🤠🤠🤠🤠🤠🤠🤠🤠🤠🤠🤠🤠🤠😎😎😎😎🤞😎😎😎😎😎🤞😎

**Comment by pta2002** [comment]
Was just thinking about the template! I can probably take care of that tomorrow though, no need to worry about it :)

**Comment by GaetanLepage** [comment]
@Alexnortung is this issue still relevant ?

**Comment by GaetanLepage** [comment]
I have just tested on the HM module and I had no error. Closing then :)
