### ISSUE TITLE
Set colorscheme after setting lua globals

### ISSUE THREAD

**Issue by Alexnortung** [pta2002/nixvim#46]
**Plugin affected**: most colorschemes (specifically nord)
**Nixpkgs channel**: 22.05
**Home-manager version**: 22.05

## Description
Before the large refactor, the nord color scheme worked fine. But now variables set has no effect.
For example setting borders and contrast on the nord colorscheme does nothing when neovim is started. since the colorscheme command is called before the globals has been set.

A fix was already made for this in #23 (https://github.com/pta2002/nixvim/pull/23/files#diff-224c83bb3598476e7aaabf84b7de2b5932e06057286163935b93f8db58e1a3acR211-R216)

It should be noted that the variables are set, since using the command `:colorscheme nord` after neovim starts will display the colorscheme with the variables defined in the config.

## Config
```
{
...
    colorschemes.nord = {
      enable = true;
      borders = true;
      contrast = true;
    };
...
}
```

**Comment by pta2002** [comment]
Should be fixed!
