### ISSUE TITLE
Plugin request: telescope-file-browser-nvim

### ISSUE THREAD

**Issue by DEEENGAN** [pta2002/nixvim#467]
**Plugin**: telescope-file-browser-nvim
**Plugin repository**: https://github.com/nvim-telescope/telescope-file-browser.nvim#mappings
**Is the plugin on nixpkgs**: https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=vimPlugins.telescope-file-browser-nvim

## Extra information
Thank you!

**Comment by Wolbyte** [comment]
I'll check it out
