### ISSUE TITLE
Generate literal lua code as a dict value

### ISSUE THREAD

**Issue by legendofmiracles** [pta2002/nixvim#5]
Hello,
I need to generate some lua code as a dictionary value. The only way to represent that in nix code is through a string, but that's always made a string in the resulting lua code. The [docs for the plugin](https://github.com/edluffy/specs.nvim/tree/a62319a224b73b70af47a48ba076d7ec67b08526#usage) I'm adding are here. Both fader and resizer have this problem

Any help would be appreciated

Cheers

**Comment by legendofmiracles** [comment]
Oh I forgot, my current code can be found [here](https://github.com/legendofmiracles/nixvim/blob/c6818986f1403049c4d8b43905f0e036e300416c/plugins/utils/specs.nix#L117)

**Comment by pta2002** [comment]
Hey, I have the `mkRaw` function on the `helpers.nix` file. This should do what you want.

For your code, I think just wrapping the `fader` value with `mkRaw` should work:

```nix
{
  # ...
  fader = helpers.mkRaw (if cfg.fader.builtin == null then cfg.fader.custom else "require(\"specs\").${cfg.fader.builtin}");
  # ...
}
```

**Comment by legendofmiracles** [comment]
Awesome, that worked!
