### ISSUE TITLE
Add `package` options for plugins

### ISSUE THREAD

**Issue by Alexnortung** [pta2002/nixvim#58]
It would be nice if I could change which version of a plugin to use (pinning or using unstable/stable) while using nixvim.

I would like to be able to do this in the same manner as in most NixOS modules in nixpkgs handles this, by adding a `package` option.

**Comment by pta2002** [comment]
Good idea, though it'd definitely be a relatively big undertaking. I can get started on it though! Also ensure that all new plugins have that option

**Comment by Alexnortung** [comment]
I can also do some work on this and will open some pull requests ;)
