### ISSUE TITLE
init.lua

### ISSUE THREAD

**Issue by dfangx** [pta2002/nixvim#63]
Hi! First of all, thanks for making this awesome project! 

I was wondering if there were any plans to simply use an init.lua rather than an init.vim, since the majority of the config is in lua there are lua alternatives for most, if not all of vim configuration. From a user standpoint, it would make the resulting nvim config file easier to read. There wouldn't be any need navigate through the various lua blocks, and I think syntax highlighting would also work properly (at least in my config, the nested lua syntax highlighting is always messed up). Thanks!

**Comment by pta2002** [comment]
Yeah, there is definitely that plan, just hasn't been a priority since there's other stuff to do, but should be pretty easy actually!
