### ISSUE TITLE
bufferline: `diagnostics_indicator` expects a function

### ISSUE THREAD

**Issue by rummik** [pta2002/nixvim#69]
**Plugin affected**: bufferline
**Nixpkgs channel**: 22.05 (though this seems to persist into unstable)
**Home-manager version**: 22.05

## Description

> Error detected while processing /nix/store/z19xva0gra1bb071aj4lcbklm5fa8d0k-home-manager-files/.config/nvim/init.lua:
> 
> E5112: Error while creating lua chunk: ...j4lcbklm5fa8d0k-home-manager-files/.config/nvim/init.lua:81: unfinished str
ing near ''function(count, level)'

Relevant lines from `init.lua`:

```lua
require('bufferline').setup{['options'] = {['diagnostics'] = 'nvim_lsp',['diagnostics_indicator'] = 'function(count, level)
  local icon = level:match("error") and " " or ""
  return " " .. icon .. count
end
'}}
```

`plugins.bufferline.diagnosticsIndicator` seems to pass as a string to `diagnostics_indicator`, but the documentation indicates it should receive a function that returns a string

https://github.com/akinsho/bufferline.nvim/blob/d631817de1b52c7b1947e25ec8b7638492914768/doc/bufferline.txt#L259-L262

## Config
```nix
{
  # ...
  plugins.bufferline = {
    enable = true;
    diagnostics = "nvim_lsp";
    diagnosticsIndicator = ''
      function(count, level)
        local icon = level:match("error") and " " or ""
        return " " .. icon .. count
      end
    '';
  };
  # ...
}

**Comment by Alexnortung** [comment]
I think the module is wrong, I can look at it later.
I will probably change the type to use string or rawType.

In your case change 

```
    diagnosticsIndicator = ''
      function(count, level)
        local icon = level:match("error") and " " or ""
        return " " .. icon .. count
      end
    '';
```

tp

```
    diagnosticsIndicator = { __raw = ''
      function(count, level)
        local icon = level:match("error") and " " or ""
        return " " .. icon .. count
      end
    ''; };
```

This doesn't work now, but this will generate the code as raw instead of a string.

From this error it seems that nixvim doesn't support multiline strings @pta2002 do you think this is the case?

**Comment by Alexnortung** [comment]
It should work with the new PR. I should also note that there is a `mkRaw` function that you can use instead of wrapping the string with `__raw`. I am not entirely sure how to use it in your own config, but that should probably be added to the documentation.

**Comment by Alexnortung** [comment]
@rummik I think it is very odd that the newlines was not escaped in your generated config, I haven't been able to reproduce it. are you using NixOS, home manager or standalone NixVim?
