### ISSUE TITLE
barbar: Configuration isn't wired in

### ISSUE THREAD

**Issue by rummik** [pta2002/nixvim#70]
**Plugin affected**: barbar
**Nixpkgs channel**: 22.05
**Home-manager version**: 22.05

## Description
Looks like the configuration for `barbar` hasn't been wired up 😅 

https://github.com/pta2002/nixvim/blob/a601a75d0cae8229f1416506bd172e4e4aef3ce7/plugins/bufferlines/barbar.nix#L51-L57

**Comment by GaetanLepage** [comment]
Fixed by https://github.com/pta2002/nixvim/pull/159 :)
