### ISSUE TITLE
Discord/community? 

### ISSUE THREAD

**Issue by volkswagenfeature** [pta2002/nixvim#78]
I'm trying to use your framework to nix-ify my vim configs, and was curious if you guys have a contributor discord, or some way to contact knowlegeable users. I'm concerned opening a issue for every noobish question would be a bit much.

**Comment by pta2002** [comment]
Don't really feel like there's enough people for a Discord, but I'll turn on the github discussions page, that way it'll show up on google too!

**Comment by volkswagenfeature** [comment]
Thanks!
