### ISSUE TITLE
nixvim.build seems not to exist, perhaps it was renamed to makeNixvim?

### ISSUE THREAD

**Issue by volkswagenfeature** [pta2002/nixvim#88]
**Plugin affected**: N/A
**Nixpkgs channel**: N/A
**Home-manager version**: N/A
## Description
In reading through the source code, it looks like at some point a function name may have been changed without totally updating the documentation. function `nixvim.build` may have been renamed to `nixvim.makeNixvim` on line 50 in file flake.nix

**Comment by volkswagenfeature** [comment]
#86 would resolve this

**Comment by pta2002** [comment]
Yeah, that's correct, sorry about that :sweat_smile: will close this issue as that issue does indeed address this
