### ISSUE TITLE
No config generated on `nixpkgs-22.11` and `nix-darwin`

### ISSUE THREAD

**Issue by gaetgu** [pta2002/nixvim#92]
**Nixpkgs channel**: unstable

Hi! I am working on getting `nix-darwin` set up on my computer from a completely fresh install, and as part of that I want to use this awesome package to set up my `nvim` config. I am using flakes, so I have put `nixvim` in the outputs.

```nix
{
  inputs = {
    # nix-darwin stuff....
    
    nixvim.url = github:pta2002/nixvim;
  };

  outputs = { self, nixvim, ... }: {
    darwinConfigurations."myHostName" = darwin.lib.darwinSystem {
      system = "aarch64-darwin";
      modules = [
        nixvim.nixosModules.nixvim
        ./hosts/myHostName/default.nix
      ];
    };
  };
}
```

And in `./hosts/myHostName/default.nix`, I have put
```nix
programs.nixvim = {
  enable = true;
  colorschemes.gruvbox.enable = true;
  options = {
    number = true;
    relativenumber = true;
  };
};
```

I can run `darwin-rebuild switch --flake .` perfectly fine without any errors, but when I look in `~/.config/` there is no `nvim` folder and when I run `nvim`, none of my settings are applied.

I am fairly new to the world of nix (I had been using `home-manager` for about half a year before now switching to a fresh `nix-darwin` with flakes), so I am almost certainly missing something obvious, but if someone could help me out that would be greatly appreciated.

If you would like to see my entire configuration, you can find it here: https://git.sr.ht/~gaetgu/maconfig/tree

**Comment by pta2002** [comment]
Ah, I feel like you want to use home-manager in this case, and not use the NixOS module, but I'm not sure. Unfortunately I don't have a Mac that I can use to test nix-darwin stuff :(

**Comment by gaetgu** [comment]
No, that doesn't work because I am not currently using home-manager (though I understand that I made that a bit confusing in my original comment), just nix-darwin and flakes. Thanks for taking a look at this, but I totally understand if you are unable to help since you don't have a mac.

**Comment by gaetgu** [comment]
First off, I edited the title to reflect the fact that I am using `nixpkgs-22.11`, not `nixos-unstable` (not sure how on earth I put that there?).

I am at a point where I am getting the same error as from #79. That is, when I start up nvim in any text file I get this error message: `E484: Can't open file /etc/nvim/syntax/syntax.vim` and I can confirm that `/etc/nvim` is totally empty. 

I am still using the `nixosModules`, as `homeManagerModules` are not available to me since I am not using home manager (though I would be willing to if you think that might help out getting this solved).

I have shortened my config file down to
```nix
programs.nixvim = {
  enable = true;
  colorschemes.gruvbox.enable = true;
};
```
but the error is the same even with the (relatively) larger config I had in the inital issue.

I am unsure why I am getting this error, as (if I understand correctly) it was only reported as an issue for `nixpkgs-22.05`. That being said, it may have something to do with the fact that I am using `nix-darwin`, I really don't know.

**Comment by pta2002** [comment]
That is... Odd. Can you try just using the standalone option? That is, add a package to the environment using `makeNixvim`.

**Comment by gaetgu** [comment]
Alright. So I removed the `nixvim.nixosModules.nixvim` module, and added this to the bottom of my outputs:
```nix
environment.systemModules = [
  (nixvim.legacyPackages."aarch64-darwin".makeNixvim {
    colorschemes.gruvbox.enable = true;
  })
];
```
I also installed neovim using `environment.systemPackages` (with nix-darwin) since using this `makeNixvim` doesn't seem to install it by itself. Following this procedure, I don't get the `E484` that I got before, but the configuration is also not applied. I am not really sure what is happening here. As always, you can find my whole config at https://git.sr.ht/~gaetgu/maconfig if you ever need it.

**Comment by pta2002** [comment]
This is pretty weird. I'll see if I can get a macOS VM or borrow a Mac or something so I can better test this.

**Comment by gaetgu** [comment]
Yes, I can confirm that running that test does run neovim with the gruvbox colorscheme. The other tests that I ran (such as with treesitter) also worked fine.

**Comment by pta2002** [comment]
Alright, so I rented out an M1 Mac Mini from Scaleway and managed to get a basic config working:

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-22.11-darwin";
    darwin.url = "github:lnl7/nix-darwin/master";
    darwin.inputs.nixpkgs.follows = "nixpkgs";

    nixvim.url = "github:pta2002/nixvim";
  };

  outputs = { self, darwin, nixpkgs, nixvim }: {
    darwinConfigurations."e4cfb838-522c-43f7-a98c-3e0d4bbb9df1" = darwin.lib.darwinSystem {
      system = "x86_64-darwin";
      modules = [
        ./configuration.nix
        {
          _module.args = { inherit nixvim; }; 
        }
      ];
    };
  };
}
```

```nix
{ pkgs, nixvim, ... }: {
  nix.useDaemon = true;
  services.nix-daemon.enable = true;

  environment.systemPackages = [ (nixvim.legacyPackages.${pkgs.system}.makeNixvim {
    colorschemes.gruvbox.enable = true;
  }) ];

  programs.zsh.enable = true;
}
```

Can you test this?

**Comment by gaetgu** [comment]
I can confirm that this configuration added onto my own works. I think that I had `environment.systemPackages` being called in the wrong place before.

I am sorry for wasting your time on this, it seems that the problem did indeed stem from not knowing that much about `nix` itself.

**Comment by pta2002** [comment]
Not really! The NixOS module is actually incompatible with nix-darwin, due to the way neovim works on MacOS (it doesn't look for the config file in the place NixVim puts it), so I added a new module `nixvim.nixDarwinModules.nixvim` specifically for usage on macOS. I've tested it on my machine and it works, but please try it out! That way you can configure it using the actual module, without needing to use `makeNixvim`.

**Comment by gaetgu** [comment]
So if I understand this correctly, I should put `nixvim.nixDarwinModules.nixvim` into my `modules` under `darwinConfigurations`, and configure neovim via a `programs.nixvim` inside my `default.nix` (like a `configuration.nix`)?

**Comment by pta2002** [comment]
Correct! There's an example in the README too
