### ISSUE TITLE
nvim-lsp: add extra arguments to servers

### ISSUE THREAD

**Issue by seghers** [pta2002/nixvim#96]
I'd like to set an additional filetype for html. How could I do this in nixvim?

``` lua
require'lspconfig'.html.setup{
  filetypes = { "html", "heex" }
}
```

**Comment by seghers** [comment]
This does work, but is there a more appropriate way to do this the `nixvim` way?
``` nix
  programs.nixvim = {
    plugins.lsp = {
      enable = true;
      servers = {
        # html.enable = true;
        elixirls.enable = true;
        tailwindcss.enable = true;
      };
    };

    extraConfigLua = ''
      require'lspconfig'.html.setup{
        filetypes = { "html", "heex" }
      }
    '';
  };
```

**Comment by pta2002** [comment]
Not at the moment. That is definitely something that I'll implement though, so thanks for bringing it to my attention.

Just for future reference, this type of question is better suited for the discussions tab! I'll change this issue to reflect the feature that I'd need to implement.
